In [1]:
import pandas as pd
## Importing Movie Lens 2M datasets

In [2]:
ratings = pd.read_csv('E:\\University Stuff\\Third year\\movie_recommender_research\\datasets\\movie_lens_2m\\ratings.csv')
movie = pd.read_csv('E:\\University Stuff\\Third year\\movie_recommender_research\\datasets\\movie_lens_2m\\movies.csv')

In [3]:
movie['year'] = movie.title.str.extract('(\\d\d\d\d\))',
expand=False)
#Removing the parentheses
movie['year'] = movie.year.str.extract('(\d\d\d\d)',expand=False)
#Removing the years from the 'title' column
movie['title'] = movie.title.str.replace('(\(\d\d\d\d\))', '')
#Applying the strip function to get rid of any ending whitespace characters that may have appeared
movie['title'] = movie['title'].apply(lambda x: x.strip())

C:\Users\Vlad\AppData\Local\Temp\ipykernel_5768\2164731462.py:6: FutureWarning: The default value of regex will change from True to False in a future version.
  movie['title'] = movie.title.str.replace('(\(\d\d\d\d\))', '')

In [4]:
movie.drop(columns=['genres'], inplace=True)

In [5]:
ratings.drop(columns=['timestamp'], inplace=True)
ratings

          userId  movieId  rating
0              1        2     3.5
1              1       29     3.5
2              1       32     3.5
3              1       47     3.5
4              1       50     3.5
...          ...      ...     ...
20000258  138493    68954     4.5
20000259  138493    69526     4.5
20000260  138493    69644     3.0
20000261  138493    70286     5.0
20000262  138493    71619     2.5

[20000263 rows x 3 columns]

In [6]:
movie

       movieId                        title  year
0            1                    Toy Story  1995
1            2                      Jumanji  1995
2            3             Grumpier Old Men  1995
3            4            Waiting to Exhale  1995
4            5  Father of the Bride Part II  1995
...        ...                          ...   ...
27273   131254        Kein Bund für's Leben  2007
27274   131256       Feuer, Eis & Dosenbier  2002
27275   131258                  The Pirates  2014
27276   131260                 Rentun Ruusu  2001
27277   131262                    Innocence  2014

[27278 rows x 3 columns]

## Create User input

In [7]:
user = [
            {'title':'Toy Story, The', 'rating':5},
            # {'title':'Toy Story', 'rating':2.5},
            # {'title':'Jumanji', 'rating':3},
            # {'title':"Pulp Fiction", 'rating':4.5},
            # {'title':'Akira', 'rating':5}
         ]
input_movie = pd.DataFrame(user)
input_movie
#Filtering out the movies by title
Id = movie[movie['title'].isin(input_movie['title'].tolist())]
#Then merging it so we can get the movieId. It's implicitly merging it by title.
input_movie = pd.merge(Id, input_movie)
input_movie.head()

   movieId                title  year  rating
0        1            Toy Story  1995     2.5
1        2              Jumanji  1995     3.0
2      296         Pulp Fiction  1994     4.5
3     1274                Akira  1988     5.0
4     1968  Breakfast Club, The  1985     4.0

## Filtering users that have rated one of the given movies

In [8]:
def filter_users(given_ratings):
    #Filtering out users that have watched movies that the input has watched and storing it
    users = given_ratings[ratings['movieId'].isin(input_movie['movieId'].tolist())]
    user_subset_group = users.groupby(['userId'])
    #Sorting it so that users with movie ratings most in common with the input will have priority
    user_subset_group = sorted(user_subset_group,  key=lambda x: len(x[1]), reverse=True)
    return user_subset_group

user_subset_group = filter_users(ratings)

In [9]:
type(user_subset_group[0][1])
print(user_subset_group[0])

(91,       userId  movieId  rating
9621      91        1     4.0
9622      91        2     3.5
9669      91      296     3.5
9826      91     1274     2.5
9903      91     1968     4.0)

In [10]:
import math
#Store the Pearson Correlation in a dictionary, where the key is the user Id and the value is the coefficient
pearsonCorDict = {}
input_movie = input_movie.sort_values(by='movieId')
#For every user group in our subset
for name, group in user_subset_group:
    #Let's start by sorting the input and current user group so the values aren't mixed up later on
    group = group.sort_values(by='movieId')
    #Get the N for the formula
    n = len(group)
    #Get the review scores for the movies that they both have in common
    temp = input_movie[input_movie['movieId'].isin(group['movieId'].tolist())]
    #And then store them in a temporary buffer variable in a list format to facilitate future calculations
    tempRatingList = temp['rating'].tolist()
    #put the current user group reviews in a list format
    tempGroupList = group['rating'].tolist()
    #Now let's calculate the pearson correlation between two users, so called, x and y
    Sxx = sum([i**2 for i in tempRatingList]) - pow(sum(tempRatingList),2)/float(n)
    Syy = sum([i**2 for i in tempGroupList]) - pow(sum(tempGroupList),2)/float(n)
    Sxy = sum( i*j for i, j in zip(tempRatingList, tempGroupList)) - sum(tempRatingList)*sum(tempGroupList)/float(n)

    #If the denominator is different than zero, then divide, else, 0 correlation.
    if Sxx != 0 and Syy != 0:
        pearsonCorDict[name] = Sxy/math.sqrt(Sxx*Syy)
    else:
        pearsonCorDict[name] = 0

In [11]:
pearsonCorDict.items()

dict_items([(91, -0.6890618270883883), (294, 0.10783277320343156), (586, 0.7836445860269199), (648, 0.444102681159703), (775, 0.46266531814837414), (812, -0.12945217625467967), (869, 0.07624928516630236), (903, 0.0660338179744212), (1200, 0.2494610901255917), (1244, 0.29654012630945475), (1715, 0.6309898162000303), (1748, 0.5114957546028552), (1763, 0.1760901812651271), (1810, 0.6990252954195334), (1813, 0.36589645615870564), (1849, 0.06603381797442423), (1864, 0.5114957546028552), (1942, 0.23262521394079627), (1984, -0.7994259492812168), (2047, 0.5477103564747346), (2099, -0.10783277320343156), (2367, -0.10783277320343994), (2397, 0), (2515, 0.9244734516419062), (2661, 0.835703992326648), (2757, 0.8439249387982215), (2959, 0.23055616708169688), (2988, 0.29809064964264287), (3179, 0.0), (3218, 0.26413527189768793), (3268, 0.7781270639007126), (3269, 0.3606167767094639), (3318, 0.3026049692947228), (3397, 0.46107317554294897), (3487, -0.3774147062120338), (3576, 0.39620290784652895), (3629, 0.5906244232186185), (3858, -0.07823011594259388), (3986, 0.12056070554260306), (4034, 0.4313310928137531), (4332, 0.26413527189768593), (4358, 0.17049858486761843), (4529, -0.12888481555661682), (4598, 0.26413527189768443), (4696, 0.37741470621203593), (5504, -0.579601155968481), (5518, 0.1968748077395395), (5576, 0.6890618270883883), (5706, 0.1968748077395395), (5791, 0.3774147062120368), (5825, 0.5075459213253782), (6057, 0.8364283610093444), (6207, 0.057639041770424365), (6233, -0.5187513759338138), (6369, 0.3774147062120368), (6630, -0.07188851546895997), (6743, 0.6827688932004708), (6976, -0.17032272243312685), (6978, 0.8357039923266462), (7083, -0.1903297204970173), (7443, 0.5114957546028552), (7539, 0.5348837209302323), (7545, 0.3509885473947315), (8032, 0.9400643223910575), (8082, 0.8859366348279278), (8207, 0.48424799847909017), (8316, 0.8069465847859308), (8405, 0.37741470621203593), (8412, 0.3328770246548887), (8417, 0.3774147062120368), (8558, 0.7271614469220996), (8623, 0.7781270639007186), (8805, -0.37741470621203405), (8944, 0.6842472173461585), (8990, 0.5498414147691564), (9145, -0.2017366461964786), (9175, 0.4176345347922785), (9305, 0.9644856443408245), (9410, 0.9244734516419048), (9454, 0.26413527189768593), (9650, 0.9510441892119876), (9772, 0.9244734516419071), (9790, -0.5647449664020139), (9795, -0.10281451514408314), (9838, 0.6819943394704737), (10012, 0.4253428648368024), (10059, 0.4928713255803919), (10178, -0.6628489803598699), (10321, -0.1950768266287071), (10387, 0.7613188819880644), (10389, 0.3774147062120368), (10443, -0.6105716541821835), (10497, -0.26413527189768593), (10514, 0.29261523994306154), (10560, 0.5402893024772932), (10621, -0.12945217625467967), (10670, 0.616315634427937), (10821, 0.2219180164365905), (10822, 0.02224420266500519), (10989, 0.057639041770424365), (11292, 0.3020824253557253), (11314, 0.5906244232186185), (11434, -0.6132846549348309), (11668, 0.5348837209302323), (11803, -0.10028244211278145), (12044, 0.6360779234376756), (12064, 0.3616821166278092), (12140, 0.8511025427814378), (12239, 0.20173664619648324), (12271, 0.6827688932004708), (12389, 0.6819943394704737), (12537, -0.835703992326648), (12618, -0.4842479984790933), (12778, -0.33845324213063116), (12783, 0.6972241607851769), (12901, 0.4205550915960004), (12944, 0.3616821166278092), (13049, 0.12056070554260306), (13064, 0.10783277320343994), (13090, -0.03336630399751095), (13110, 0.9418604651162791), (13174, 0.6340294594746582), (13338, 0.12945217625467967), (13431, 0.5917813771642481), (14032, 0.044022545316281844), (14083, -0.29531221160930926), (14139, 0.46107317554294897), (14159, 0.6819943394704737), (14285, 0.37741470621203427), (14506, 0.8439249387982215), (14512, 0.8670576155975179), (14544, 0.4441026811597037), (14551, 0.4928713255803919), (14866, -0.5178087050187182), (14916, 0.10783277320343741), (15030, 0.24468622931506975), (15308, 0.5917813771642448), (15361, 0.835703992326648), (15486, 0.729786776593059), (15503, -0.017972128867238715), (15682, 0.4313310928137521), (15694, 0.6819943394704737), (15753, -0.9244734516419016), (15822, 0.4921870193488488), (15939, 0.04402254531627865), (15944, -0.6819943394704737), (16351, 0.6177432843242373), (16453, 0.444102681159703), (16824, 0.24041118447297743), (16840, -0.1903297204970173), (16865, 0.1858261556206655), (16938, 0.8364283610093444), (16956, 0.14794534429106385), (16974, 0.5114957546028552), (17133, 0.17609018126512427), (17163, 0.296540126309456), (17250, 0.5796011559684829), (17357, 0), (17488, 0.444102681159703), (17635, -0.6628489803598699), (17842, 0.6163156344279365), (17918, 0.32160095239694025), (18057, 0.4313310928137521), (18138, 0.15640942485936943), (18191, 0.5114957546028552), (18338, 0.3451057175812338), (18390, 0.43133109281375515), (18471, 0.23262521394079627), (18496, 0.7223870690923445), (18611, -0.4313310928137521), (18706, 0.6102745452006318), (18901, -0.021147746721889477), (18964, 0.3002967359775859), (18977, 0.38492560807137777), (19008, 0.10783277320343994), (19212, -0.6819943394704737), (19290, 0.276358837723999), (19377, 0.5202048710098849), (19711, 0.17049858486761843), (19776, -0.17049858486761843), (19837, 0.6450818772851885), (19995, 0.39620290784653284), (20011, 0.7916331135924708), (20083, 0.7009130258223482), (20127, 0.815378857500335), (20132, -0.6518620757676149), (20158, -0.17049858486761843), (20165, 0.023531040266749247), (20294, 0.5062592711372335), (20388, -0.276358837723999), (20619, -0.09539445011233319), (20656, 0.8364283610093426), (20820, 0.9510441892119876), (21349, 0.02695819330085807), (21378, -0.09539445011233319), (21690, 0.518751375933811), (21768, 0.4313310928137521), (21806, 0.9244734516419062), (21861, 0.17609018126512427), (21885, 0.3383639475502502), (21922, 0.5114957546028552), (22141, 0.6890618270883883), (22189, 0.2017366461964786), (22205, 0.6890618270883883), (22231, 0.78178760572493), (22253, 0.6102745452006318), (22411, -0.1760901812651271), (22650, -0.04402254531627865), (22901, 0.6890618270883883), (23101, 0.29261523994306154), (23130, 0.6028035277130154), (23171, -0.2326252139407966), (23180, 0.5364612732289447), (23319, 0.37741470621203593), (23459, -0.23055616708169335), (23488, 0.6890618270883883), (23646, 0.3143838566185041), (23877, 0.9567085882496863), (24027, 0.6028035277130154), (24109, 0.7190233885442854), (24112, 0.7545253113928223), (24135, 0.6028035277130154), (24233, 0.29686241759717696), (24347, 0.6819943394704737), (24425, 0.2219180164365905), (24661, 0.39620290784653284), (24688, 0.518751375933811), (24718, 0.916578572229228), (24905, 0.4313310928137521), (25147, 0.21304071579547132), (25180, -0.5917813771642448), (25192, 0.7724016533656629), (25286, 0.8108528259548389), (25411, 0.6028035277130154), (25455, 0.78178760572493), (25464, 0.4695738167069976), (25607, 0.5498414147691564), (25614, -0.21237274928075897), (25825, 0.32160095239694025), (25901, -0.0864585626556345), (25978, 0.29531221160930926), (25992, 0.05763904177042012), (26012, -0.838742136829326), (26185, 0.0864585626556345), (26223, -0.23055616708169335), (26277, 0.512205672716334), (26623, 0.32221203889154204), (26640, 0.5943043617697931), (26647, 0.617743284324239), (26833, -0.021147746721889477), (27041, 0.6990252954195334), (27119, 0.37741470621203593), (27251, -0.64699663922062), (27531, 0.3774147062120368), (27809, 0.10783277320343994), (27993, 0.359850803004291), (28222, 0.02114774672188951), (28860, 0.4441026811597037), (29357, -0.3458342506225371), (29420, 0.6044463231180845), (29499, -0.17609018126512427), (29575, 0.7771889263740456), (29656, 0.860465116279071), (29738, 0.39238950911622944), (29819, 0.2219180164365905), (30428, 0.31141883731009007), (30447, 0.46107317554294897), (30519, -0.02644660613471573), (30576, 0.9207975983104345), (30664, 0.8038925870986305), (30857, 0.3458342506225421), (30896, 0.5114957546028552), (31106, 0.3143838566185041), (31151, -0.5348837209302323), (31347, 0.7781270639007126), (31673, 0.9801379059282862), (31753, 0.10783277320343994), (31775, 0.6163156344279422), (32094, 0.43133109281375515), (32549, 0.015899075018721433), (32710, 0.02695819330085807), (32861, 0.6819943394704737), (32935, 0.39620290784653517), (32962, 0.8789953869989582), (33075, 0.6340294594746598), (33190, 0.0), (33308, 0.4441026811597037), (33344, 0.6842472173461618), (33349, 0.5406491687377103), (33376, 0.9676228159277812), (33402, 0.8364283610093444), (33624, 0.9666361166746261), (33954, 0.46380629477160623), (34140, 0.5930232558139532), (34202, -0.4232028331561082), (34334, 0.5519691272882647), (34382, 0.4068496968004207), (34485, 0.6493325434151487), (34494, 0.04402254531627891), (34576, 0.1903297204970176), (34587, 0.6643711789971691), (34632, 0.13391114177635238), (34651, 0.3746537715077522), (34674, 0.6628489803598699), (34700, 0.7304801374371186), (34813, 0.9244734516419065), (34823, 0.48424799847909017), (34971, 0.5442477655948239), (35004, -0.015899075018721443), (35022, -0.6628489803598699), (35055, 0.22093023255814026), (35091, 0.0864585626556345), (35098, -0.21237274928075897), (35227, 0.24262373970773848), (35241, -0.7263719977186395), (35356, 0.9777538105996068), (35780, 0.4452936263957637), (35827, 0.7040710434833449), (35834, 0.704360725060496), (35976, -0.1760901812651271), (36048, 0.6990252954195334), (36128, -0.3774147062120338), (36204, -0.5084957536268602), (36292, 0.78178760572493), (36481, -0.8876720657463726), (36628, -0.4872402905909916), (36683, -0.5114957546028552), (37069, 0.8691788977099857), (37179, 0.33081584678942483), (37253, -0.2671199459776677), (37331, 0.6028035277130154), (37360, 0.4921870193488488), (37547, 0.48224282217041226), (37577, 0.22874785549890708), (37823, 0.8247621221537389), (37991, 0.26413527189768443), (38031, 0.6163156344279349), (38082, 0.1968748077395395), (38148, 0.22874785549890708), (38156, 0.7545253113928223), (38251, 0.8247621221537389), (38296, 0.4899318550485956), (38398, 0.26413527189768443), (38455, 0.5498414147691573), (38492, 0.5114957546028552), (38666, 0.0), (38710, 0.3746537715077522), (38756, -0.04402254531627865), (38852, 0.7009130258223497), (38920, 0.6163156344279365), (39154, -0.0864585626556345), (39181, -0.17609018126512427), (39198, 0.9244734516419016), (39346, 0.05763904177042012), (39381, 0.057639041770424324), (39382, 0.48993185504860093), (39551, -0.8096711066328952), (39556, 0.12688648033134287), (39647, -0.5178087050187182), (39734, 0.6628489803598699), (39745, 0.9244734516419065), (39937, 0.8670576155975166), (39968, 0.02114774672188951), (40105, 0.17049858486761843), (40206, 0.463806294771608), (40483, 0.1858261556206655), (40523, 0.41337595048678016), (40768, 0.43133109281375515), (40847, 0.9611540777559279), (40917, 0.1903297204970176), (41096, -0.5187513759338138), (41127, 0.7190233885442854), (41165, -0.22258705026211378), (41283, 0.0), (41468, 0.6028035277130154), (41517, 0.9644856443408245), (41713, 0.4928713255803919), (41714, -0.1760901812651271), (41816, 0.7781270639007186), (41877, 0.4313310928137521), (41929, 0.044022545316281775), (41941, 0.7122586574476206), (42032, -0.017972128867238733), (42033, 0.36581939815188935), (42096, -0.2558083306475755), (42204, 0.6842472173461585), (42424, -0.04876920665717847), (42449, 0.04402254531627865), (42456, -0.6819943394704737), (42598, 0.3020824253557255), (42640, -0.2017366461964786), (42671, 0.25438520029955664), (42692, -0.1374603536922891), (42726, 0.6264518021884178), (42788, 0.20173664619648324), (42909, 0.9644856443408245), (42913, 0.6827688932004708), (42933, 0.867523903935253), (43194, 0.27842302319485235), (43210, 0.34147044847755637), (43229, 0.9644856443408245), (43331, 0.4313310928137531), (43517, 0.5062592711372358), (43525, 0.48424799847909017), (43657, 0.7836445860269199), (43845, 0.4313310928137531), (43864, 0.6309898162000319), (43883, 0.49287132558039265), (43945, 0.444102681159703), (43970, -0.24112141108520613), (44070, -0.2017366461964786), (44296, -0.64699663922062), (44341, 0.8615893176101221), (44438, 0.17049858486761843), (44530, 0.64699663922062), (44846, 0.8876720657463726), (44870, 0.646996639220632), (45015, -0.06444240777830841), (45298, -0.8691788977099857), (45357, -0.6163156344279386), (45388, -0.22874785549890708), (45406, 0.23262521394079627), (45461, 0.8876720657463726), (45477, -0.09435367655300707), (45538, 0.8069465847859288), (45788, 0.14794534429106138), (45815, -0.9244734516419059), (45929, 0.7817876057249318), (46219, 0.29654012630945475), (46281, -0.4068496968004177), (46367, 0.21310018948965792), (46470, 0.0325128044381159), (46929, -0.03698633607276333), (46947, 0), (46982, 0.02695819330085807), (47052, 0.5908001781468405), (47422, -0.39620290784652895), (47542, 0.835703992326648), (47559, 0.10783277320343741), (47577, 0.11379481553341267), (47589, 0.5114957546028552), (47634, 0.6518358737330687), (47643, 0.10783277320343994), (47712, -0.6388923334787893), (47840, -0.48424799847909017), (47890, 0.9244734516419016), (48033, 0.3458342506225421), (48062, -0.017972128867238733), (48083, 0.19076436303722014), (48345, 0.9244734516419071), (48410, -0.4313310928137521), (48527, 0.46380629477160823), (48565, 0.26413527189768443), (48677, -0.31438385661850704), (48821, 0.4313310928137521), (48885, 0.4313310928137531), (48904, 0.78178760572493), (48929, 0.7767130575280721), (48944, -0.30373569952270396), (49321, 0.4313310928137531), (49374, 0.6340294594746598), (49490, 0.2017366461964786), (49554, 0.5114957546028552), (49668, 0.46380629477160623), (49758, -0.0864585626556345), (49904, 0.5062592711372358), (50071, 0.6028035277130154), (50396, 0.10783277320344019), (50552, 0.5114957546028552), (50567, 0.7043607250604985), (50570, 0.7831245129728023), (50645, 0.6102745452006318), (50774, -0.12945217625467967), (50943, 0.4746748334074818), (51608, 0.9244734516419016), (51703, 0.0864585626556345), (51782, 0.4921870193488488), (51830, 0.4921870193488488), (51965, 0.5697674418604661), (51992, -0.4899318550485956), (52075, -0.13813650314199372), (52106, 0.8367179328930429), (52225, 0.28614654455582733), (52260, -0.37465377150775536), (52366, 0.6028035277130154), (52410, 0.513208595745258), (52512, -0.29809064964264287), (52636, -0.9510441892119876), (52726, 0.9244734516419016), (52740, 0.24262373970773848), (52810, 0.9510441892119893), (52877, 0.6168870908644989), (53346, -0.05547950410914768), (53413, -0.1760901812651271), (53640, -0.2526953636051604), (54095, 0.31438385661850676), (54107, 0.21304071579546996), (54214, 0.46107317554294897), (54259, 0.455139494246195), (54421, 0.27842302319485235), (54456, 0.4313310928137521), (54465, 0.6819943394704737), (54469, 0.26413527189768443), (54612, 0.4313310928137531), (55237, 0.7436287815900663), (55420, -0.23055616708169335), (55651, 0.037605915792293935), (55914, -0.10783277320343845), (55993, 0.13005121775247064), (56451, 0.27842302319485235), (56457, 0.7781270639007126), (56472, 0.46266531814837414), (56520, 0.512205672716334), (56603, 0.5059173657351389), (56718, -0.8524929243380921), (56720, -0.16019234629265416), (56753, 0.7172806257026124), (57053, 0.2326252139407966), (57248, 0.880634314494749), (57441, 0.25219263977090295), (57475, 0.27842302319485235), (57587, 0.4551792621336503), (57830, 0.17488982520594493), (57849, 0.6099942813304189), (57903, -0.31438385661850704), (58184, 0.9150772842791192), (58213, 0.7674418604651161), (58313, 0.4313310928137521), (58346, 0.43133109281375476), (58424, -0.7088664855613924), (58612, 0.11366572324507894), (58648, 0.0), (58785, -0.1760901812651271), (58831, 0.9030994755787951), (58846, 0.7190233885442854), (58876, -0.24112141108520613), (58995, 0.1194596714704281), (59118, 0.3842147276763073), (59137, -0.374191635188391), (59362, 0.626166801516251), (59407, 0.03698633607276333), (59447, 0.6995593008237843), (59457, -0.036986336072765996), (59477, -0.06444240777830841), (59702, 0.22327898845112473), (59917, -0.6469966392206296), (59971, 0.4313310928137531), (60035, -0.4313310928137531), (60267, -0.4068496968004207), (60363, 0.7817876057249286), (60441, 0.46107317554294897), (60584, -0.384994532607014), (60666, 0.0660338179744212), (60762, 0.044022545316281775), (60911, 0.9616447378918993), (60978, 0.24041118447297505), (61000, -0.02114774672188951), (61053, 0.8453329153910596), (61062, -0.46712825596513435), (61121, 0.4441026811597037), (61509, -0.17049858486761843), (61552, 0.7433046224826583), (61696, 0.5114957546028552), (61740, -0.09435367655300707), (61763, 0.5075459213253782), (61767, 0.6995593008237843), (61824, 0.09843740386976975), (61993, 0.02114774672188951), (62022, 0.057639041770424365), (62040, 0.26413527189768876), (62089, -0.5187513759338097), (62235, 0.518751375933811), (62387, 0.9231344105977692), (62430, 0.5114957546028552), (62641, 0.7907736701585503), (62725, -0.2326252139407966), (62779, 0.0), (62805, 0.6842472173461585), (62901, 0.4441026811597037), (62925, 0.48424799847909467), (62984, 0.7190233885442854), (63247, 0.78178760572493), (63365, 0.9424040749333705), (63525, 0.6769381383324209), (63546, 0.48993185504860093), (63618, -0.0635963000748903), (63705, 0.26413527189768443), (63828, 0.43133109281375687), (63834, 0.3143838566185041), (63858, 0.7781270639007126), (64430, -0.09539445011233319), (64483, 0.7817876057249318), (64577, 0.026958193300858132), (64908, -0.26413527189768443), (64940, 0.7781270639007186), (65180, 0.3746537715077522), (65185, 0.6993160471563451), (65295, -0.0660338179744212), (65317, 0.5075459213253782), (65331, 0.037605915792293935), (65469, -0.4253428648368024), (65527, -0.5114957546028552), (65742, 0.03698633607276333), (65777, -0.48424799847909017), (65852, 0.37741470621203593), (65937, 0.2736054748444889), (66011, 0.9644856443408245), (66041, -0.518751375933811), (66049, 0.512205672716334), (66226, 0.357985098440644), (66263, -0.24041118447297505), (66533, 0.779054675917396), (66617, 0.520165791652055), (66749, 0.4253428648368024), (66784, 0.9244734516419016), (66825, 0.6085582902189937), (66834, -0.6340294594746583), (66836, 0.6995593008237837), (66952, -0.10271927240465442), (67053, 0.22093023255814034), (67196, 0.10783277320344019), (67283, 0.7803073065148277), (67387, 0.10783277320343994), (67562, 0.2441860465116274), (67596, 0.11366572324507894), (67602, 0.4342769752451438), (67657, -0.04402254531627865), (68214, 0.3770512132005967), (68215, 0.7009130258223482), (68233, 0.8570106177226002), (68341, 0.46380629477160623), (68351, 0.2558083306475755), (68358, -0.518751375933811), (68364, 0.5062592711372335), (68491, 0.5114957546028552), (68497, 0.26413527189768793), (68501, 0.37741470621203593), (68558, 0.39534883720930325), (68653, 0.9021937088963177), (68710, 0.35590724264010204), (68768, 0.544205170031946), (69040, -0.1903297204970173), (69346, 0.8876720657463708), (69378, 0.1968748077395395), (69392, -0.23055616708169335), (69494, 0.10783277320344019), (69538, -0.1760901812651271), (69662, 0.3023255813953484), (69664, 0.48993185504860093), (69683, 0.7781270639007186), (69702, -0.3383639475502502), (69793, 0.9698435761420623), (69820, 0.057639041770424365), (69892, 0.17049858486761843), (70037, -0.5455484570732912), (70143, 0.04402254531628285), (70260, 0.05763904177042012), (70544, 0.4253428648368046), (70721, 0.10783277320343994), (70816, 0.0), (70854, -0.11013223807619957), (71010, -0.4068496968004177), (71036, 0.8511025427814378), (71138, 0.7043607250605006), (71170, 0.08079571632467886), (71189, 0.44670257372078165), (71267, 0.5202048710098821), (71315, 0.0), (71498, -0.4551792621336484), (71671, 0.0), (71686, 0.6819943394704737), (71699, 0.5227387626276505), (71781, 0.2757767158101437), (71975, 0.12056070554260306), (72212, 0.4313310928137531), (72253, 0.4253428648368024), (72266, 0.5405685506365604), (72347, 0.5906244232186185), (72508, 0.7009130258223508), (72517, 0.7441168295606798), (72947, -0.29531221160930926), (72992, 0.07624928516630236), (73074, 0.6827688932004737), (73213, 0.5062592711372335), (73361, 0.8255813953488371), (73478, 0.7009130258223497), (73489, -0.10783277320

In [12]:
pearsonDF = pd.DataFrame.from_dict(pearsonCorDict, orient='index')
pearsonDF.columns = ['similarityIndex']
pearsonDF['userId'] = pearsonDF.index
pearsonDF.index = range(len(pearsonDF))
pearsonDF.head()

   similarityIndex  userId
0        -0.689062      91
1         0.107833     294
2         0.783645     586
3         0.444103     648
4         0.462665     775

In [13]:
topUsers=pearsonDF.sort_values(by='similarityIndex', ascending=False)[0:50]
topUsers.head()

       similarityIndex  userId
17821              1.0  114862
16902              1.0  105389
8106               1.0   11718
14910              1.0   83705
16850              1.0  104656

In [14]:
topUsersRating=topUsers.merge(ratings, left_on='userId', right_on='userId', how='inner')
topUsersRating.head()

   similarityIndex  userId  movieId  rating
0              1.0  114862        2     2.0
1              1.0  114862        9     1.0
2              1.0  114862       10     4.0
3              1.0  114862       18     4.0
4              1.0  114862       24     4.0

In [15]:
#Multiplies the similarity by the user's ratings
topUsersRating['weightedRating'] = topUsersRating['similarityIndex']*topUsersRating['rating']
topUsersRating.head()

   similarityIndex  userId  movieId  rating  weightedRating
0              1.0  114862        2     2.0             2.0
1              1.0  114862        9     1.0             1.0
2              1.0  114862       10     4.0             4.0
3              1.0  114862       18     4.0             4.0
4              1.0  114862       24     4.0             4.0

In [16]:
#Applies a sum to the topUsers after grouping it up by userId
tempTopUsersRating = topUsersRating.groupby('movieId').sum()[['similarityIndex','weightedRating']]
tempTopUsersRating.columns = ['sum_similarityIndex','sum_weightedRating']
tempTopUsersRating.head()

         sum_similarityIndex  sum_weightedRating
movieId
1                       24.0                49.0
2                       32.0                63.0
3                        7.0                18.0
4                        4.0                 7.5
5                        7.0                20.0

In [17]:
#Creates an empty dataframe
recommendation_df = pd.DataFrame()
#Now we take the weighted average
recommendation_df['weighted average recommendation score'] = tempTopUsersRating['sum_weightedRating']/tempTopUsersRating['sum_similarityIndex']
recommendation_df['movieId'] = tempTopUsersRating.index
recommendation_df.head()

         weighted average recommendation score  movieId
movieId
1                                     2.041667        1
2                                     1.968750        2
3                                     2.571429        3
4                                     1.875000        4
5                                     2.857143        5

In [18]:
recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
recommendation_df.head(10)

         weighted average recommendation score  movieId
movieId
2208                                       5.0     2208
5500                                       5.0     5500
81819                                      5.0    81819
2621                                       5.0     2621
6001                                       5.0     6001
182                                        5.0      182
6104                                       5.0     6104
6301                                       5.0     6301
506                                        5.0      506
195                                        5.0      195

In [ ]:
movie.loc[movie['movieId'].isin(recommendation_df.head(5)['movieId'].tolist())]